### ISSUE TITLE
发现一个新的问题

### ISSUE THREAD

**Issue by Zhuwenxue2002** [huangqian8/SwitchScript#10]
老大，连接中sys-patch补丁的版本为1.5.2
拉取整合包中的版本为1.5.0

还有，咱们整合包的破解方法是基于
大气层+hekate+sigpatch的方式
还是
大气层+hekate+tesla+syspatch 四件套的方式加载的

亦或者是两个方式都安装了，确保破解游戏的稳定运行？

**Comment by Zhuwenxue2002** [comment]
还有，现在主机性能已经不够强大，但可以作为串流机使用
推荐集成插件moonlight ，非常好用
https://github.com/XITRIX/Moonlight-Switch/releases/tag/v1.0.0

**Comment by huangqian8** [comment]
两者作为互补都集成了，sys-patch已更新为1.5.2。
moonlight已集成。

**Comment by FunnyFly-ZW** [comment]
> 两者作为互补都集成了，sys-patch已更新为1.5.2。 Moonlight已集成。

更换最新整合包也注意到了三件套变成两件套的情况，开机时会提示缺少sigpatch按电源键继续，启动后可以看到sys-patch已经生效。有没有办法让sigpatch和sys-patch共存，开机不让大气层报错？

**Comment by Zhuwenxue2002** [comment]
我fork过来的项目同样集成了两个，但是开机也提示这个，或许说明sigpatch已经失效了？

**Comment by FunnyFly-ZW** [comment]
sigpatch和sys-patch都包含一个atmosphere\contents\420000000000000B文件夹，安装时会相互覆盖，不能共存，所以想问问大佬有没有共存的办法。

**Comment by Zhuwenxue2002** [comment]
sigpatch里面自带了syspatch 这不是冲突，而是覆盖更新。我找到作者删除sigpatch的原因了，是因为sigpatch的网站通讯出了问题，无法拉取sigpatch了

**Comment by FunnyFly-ZW** [comment]
> 我fork过来的项目同样集成了两个，但是开机也提示这个，或许说明sigpatch已经失效了？

sigpatch和sys-patch都包含一个atmosphere\contents\420000000000000B文件夹，安装时会相互覆盖，不能共存，所以想问问大佬有没有共存的办法。

**Comment by Zhuwenxue2002** [comment]
> > 我fork过来的项目同样集成了两个，但是开机也提示这个，或许说明sigpatch已经失效了？
> 
> sigpatch和sys-patch都包含一个atmosphere\contents\420000000000000B文件夹，安装时会相互覆盖，不能共存，所以想问问大佬有没有共存的办法。
在之前的整合包版本中，这两个补丁插件一直是兼容运行的，说明不是安装覆盖的问题， 而且你打开4200000000000B文件夹会发现里面就是syspatch而不是sigpatch

**Comment by FunnyFly-ZW** [comment]
> 我fork过来的项目同样集成了两个，但是开机也提示这个，或许说明sigpatch已经失效了？

sigpatch和sys-patch都包含一个atmosphere\contents\420000000000000B文件夹，安装时会相互覆盖，不能共存，所以想问问大佬有没有共存的办法。

**Comment by FunnyFly-ZW** [comment]
> sigpatch里面自带了syspatch 这不是冲突，而是覆盖更新。我找到作者删除sigpatch的原因了，是因为sigpatch的网站通讯出了问题，无法拉取sigpatch了

不不，那个网站正常的，是他的sigpatch.zip没有及时更新

**Comment by Zhuwenxue2002** [comment]
对 没更新sigpatch，还是只支持18.0.0和1.7.0版本呢
https://hackintendo.com/download/sigpatches/
你看这个大佬发布的sigpatch，他就是没有包含syspatch，但是是最新版本的

**Comment by Zhuwenxue2002** [comment]
我和huangqian8大佬可以将这个人的最新的sigpatches 扔到我们的插件库中，然后手动拉取手动更新，不过那样就会很麻烦啦

**Comment by FunnyFly-ZW** [comment]
> 对 没更新sigpatch，还是只支持18.0.0和1.7.0版本呢 https://hackintendo.com/download/sigpatches/ 你看这个大佬发布的sigpatch，他就是没有包含syspatch，但是是最新版本的

确实不错，回头试下

**Comment by Zhuwenxue2002** [comment]
可以尝试一下我的拉取整合
https://github.com/Zhuwenxue2002/SwitchScript
再次感谢huangqian8大佬的整合，

**Comment by FunnyFly-ZW** [comment]
> 可以尝试一下我的拉取整合 https://github.com/Zhuwenxue2002/SwitchScript 再次感谢huangqian8大佬的整合，

我看了[AK大佬的说明](https://github.com/AK478BB/Sigpatches)，按照四件套的模式，是不是hekate_ipl.ini中的fss0引导不需要设置kip1patch=nosigchk了，这一行可以去掉，这样开机就不会报nosigchk错误了，也不用集成sigpatch了

**Comment by Zhuwenxue2002** [comment]
可以尝试欸，  不过报错也无所谓啦哈哈哈哈哈，我考虑了一下，在我的整合里也删掉了sigpatches ，因为这个玩意需要一个小版本一更新，十分不好用。
而syspatch，开发者说了这样一段话：该程序在系统启动期间修补 FS、ES 和 Loader，允许自动支持固件和 Atmosphere 的未来版本，具有类似的目标，即使用签名补丁而不需要 sigpatch 文件。只有当固件或 Atmosphere 的加载器出现重大故障时，该软件才需要更新，最后一次对应用程序的更新是从固件版本 15.0.0 开始的，此后无需更新即可应用补丁。
总结一下就是这玩意不用更新

**Comment by Zhuwenxue2002** [comment]
> > 可以尝试一下我的拉取整合 https://github.com/Zhuwenxue2002/SwitchScript 再次感谢huangqian8大佬的整合，
> 
> 我看了[AK大佬的说明](https://github.com/AK478BB/Sigpatches)，按照四件套的模式，是不是hekate_ipl.ini中的fss0引导不需要设置kip1patch=nosigchk了，这一行可以去掉，这样开机就不会报nosigchk错误了，也不用集成sigpatch了

非常正确，我会在脚本中删掉生成这一行，提示huangqian8大佬也来删除

**Comment by FunnyFly-ZW** [comment]
> 可以尝试欸， 不过报错也无所谓啦哈哈哈哈哈，我考虑了一下，在我的整合里也删掉了sigpatches ，因为这个玩意需要一个小版本一更新，十分不好用。 而syspatch，开发者说了这样一段话：该程序在系统启动期间修补 FS、ES 和 Loader，允许自动支持固件和 Atmosphere 的未来版本，具有类似的目标，即使用签名补丁而不需要 sigpatch 文件。只有当固件或 Atmosphere 的加载器出现重大故障时，该软件才需要更新，最后一次对应用程序的更新是从固件版本 15.0.0 开始的，此后无需更新即可应用补丁。 总结一下就是这玩意不用更新

我刚刚测试过了，两种方法都可行！

1. 纯sys-patch：当前整合包模式，bootloader/hekate_ipl.ini中的2行kip1patch=nosigchk删除，开机不报错。效果如图，均为绿色，均由sys-patch修正。
![IMG_4036](https://github.com/huangqian8/SwitchScript/assets/41453032/c5e9ceb8-f551-4be0-904b-cdd15728a961)

2. sigpatch + sys-patch：补充最新[sigpatch](https://hackintendo.com/download/sigpatches)，bootloader/hekate_ipl.ini不用改动，开机同样不报错。效果如图，fs、es、ldr为橙色，由sigpatch修正；nifm为绿色，由sys-patch修正。
![IMG_4035](https://github.com/huangqian8/SwitchScript/assets/41453032/691b424f-4b3c-4467-bf5c-442ca6b7770e)

**Comment by Zhuwenxue2002** [comment]
> > 可以尝试欸， 不过报错也无所谓啦哈哈哈哈哈，我考虑了一下，在我的整合里也删掉了sigpatches ，因为这个玩意需要一个小版本一更新，十分不好用。 而syspatch，开发者说了这样一段话：该程序在系统启动期间修补 FS、ES 和 Loader，允许自动支持固件和 Atmosphere 的未来版本，具有类似的目标，即使用签名补丁而不需要 sigpatch 文件。只有当固件或 Atmosphere 的加载器出现重大故障时，该软件才需要更新，最后一次对应用程序的更新是从固件版本 15.0.0 开始的，此后无需更新即可应用补丁。 总结一下就是这玩意不用更新
> 
> 我刚刚测试过了，两种方法都可行！
> 
> 1. 纯sys-patch：当前整合包模式，bootloader/hekate_ipl.ini中的2行kip1patch=nosigchk删除，开机不报错。效果如图，均为绿色，均由sys-patch修正。
>    ![IMG_4036](https://private-user-images.githubusercontent.com/41453032/341275459-c5e9ceb8-f551-4be0-904b-cdd15728a961.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njg2OTgsIm5iZiI6MTcxODg2ODM5OCwicGF0aCI6Ii80MTQ1MzAzMi8zNDEyNzU0NTktYzVlOWNlYjgtZjU1MS00YmUwLTkwNGItY2RkMTU3MjhhOTYxLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMTYzMjA2MzE3M2M1Y2U3YzZmMTQ5OGMzNWE5MGM2N2U0ODA5YTdhMGQ3MDJhOTRkMWYzZWZmM2ZmZjNiMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yvV8pPu_yCqhAdYNpk2LqbSOXNUijatYI_2NFTnRhdA)
> 2. sigpatch + sys-patch：补充最新[sigpatch](https://hackintendo.com/download/sigpatches)，bootloader/hekate_ipl.ini不用改动，开机同样不报错。效果如图，fs、es、ldr为橙色，由sigpatch修正；nifm为绿色，由sys-patch修正。
>    ![IMG_4035](https://private-user-images.githubusercontent.com/41453032/341276396-691b424f-4b3c-4467-bf5c-442ca6b7770e.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njg2OTgsIm5iZiI6MTcxODg2ODM5OCwicGF0aCI6Ii80MTQ1MzAzMi8zNDEyNzYzOTYtNjkxYjQyNGYtNGIzYy00NDY3LWJmNWMtNDQyY2E2Yjc3NzBlLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA3MjYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMTYxMGQxZTY5YmUwYjQxNzEyZTY3YjI0ZGZjZmMyMmM3MDZmOGI1MDg0ZDg0ZmZlZTNhODRkNDkzMTIwMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BnJ4w1jtPrd41ywGClnCWo47knBJRC0tbDYh4UbvGG0)

嗯 我也尝试了，你这个办法超棒，我的整合包里面已经删掉sigpatches只用syspatch了，并且优化了ini文件，启动也不报错了

**Comment by huangqian8** [comment]
好奇怪，我没发现启动报错嘛。删除sigpatches是我发现这玩意不好使了，好多游戏都无法正常启动；仅保留syspatch正常。

**Comment by huangqian8** [comment]
看到报错了，因为我平时一直用的是自动识别，其他几个选项不使用，所以没有发现这个提示。

**Comment by FunnyFly-ZW** [comment]
> 好奇怪，我没发现启动报错嘛。删除sigpatches是我发现这玩意不好使了，好多游戏都无法正常启动；仅保留syspatch正常。

不好使是因为没有更新，不支持大气层1.7.1了，用上面我链接的法语网站里的就正常了，其实我觉得还是两者同时存在比较好，sys-patch作为保底手段，在sigpatch没更新不能生效的情况下，确保可以玩游戏，这样sigpatch也不用追着更。而如果只有sys-patch，一旦固件大动失效就歇菜了（当然作者也说了固件一般不会大动，上次是大动是15.0.0）

**Comment by huangqian8** [comment]
我后续再考虑把它加回去吧。

**Comment by huangqian8** [comment]
两位知道如何汉化ovl插件吗？

**Comment by Zhuwenxue2002** [comment]
> 两位知道如何汉化ovl插件吗？

应该不是很难，ovl对应的结构里面有lang文件夹，直接写json文件即可，但是ovl插件本身需不需要更改什么操作就不得而知了，可以试试

**Comment by Zhuwenxue2002** [comment]
有些不支持多语言的ovl插件是zdm改造源码，通过读取lang文件夹下的json实现的多语言支持。通过lang文件夹下的json支持多语言并不是tesla ovl的官方标准。
所以做汉化可以看下ovl插件的源码，检查一下是否支持从lang文件夹下读取i18n配置。如果没有，就需要自己改造。另外zdm好像对常用的ovl都做了多语言的支持，使用他的fork版本就行了
——以上来自E.W.大佬

**Comment by huangqian8** [comment]
> 有些不支持多语言的ovl插件是zdm改造源码，通过读取lang文件夹下的json实现的多语言支持。通过lang文件夹下的json支持多语言并不是tesla ovl的官方标准。 所以做汉化可以看下ovl插件的源码，检查一下是否支持从lang文件夹下读取i18n配置。如果没有，就需要自己改造。另外zdm好像对常用的ovl都做了多语言的支持，使用他的fork版本就行了 ——以上来自E.W.大佬

感谢解惑！
