### ISSUE TITLE
大佬，又想问几个问题

### ISSUE THREAD

**Issue by Zhuwenxue2002** [huangqian8/SwitchScript#11]
我看到咱们的脚本拉去了zdm大佬的tesla插件终极版，但脚本在实际拉取的时候拉的是您的库中插件，我想问的是，您库中插件也是有脚本去拉取zdm大佬的tesla插件还是需要您手动将插件更新到库呢

**Comment by huangqian8** [comment]
插件是论坛发布的，我手动更新到库中。

**Comment by Zhuwenxue2002** [comment]
明白了 ，我将clone一份您的项目，然后尝试维护自己的脚本整合包。
如果huangqiang大佬您有时间的话，是否可以给我一个联系方式，我想向您请教一些类似问题
我也会尝试联系zdm大佬，问问有没有github的他的插件的拉取链接，这样就不用咱们手动维护了，他的更新还是很频繁很及时的
