### ISSUE TITLE
固件18.1.0与ldn_mitm不兼容致开机报错

### ISSUE THREAD

**Issue by FunnyFly-ZW** [huangqian8/SwitchScript#13]
更新固件至18.1.0后，开机报错。移除atmosphere\contents\4200000000000010后可正常启动。
![IMG_4037](https://github.com/huangqian8/SwitchScript/assets/41453032/939ba240-4c90-461d-9577-48f244348f4f)

大佬看看ldn_mitm是不是有更新，或者Readme备注下这玩意暂时和18.1.0不兼容

**Comment by huangqian8** [comment]
更新了ldn_mitm，应该正常了。

**Comment by FunnyFly-ZW** [comment]
已测试，没问题了👍

**Comment by FunnyFly-ZW** [comment]
已测试，没问题了👍
