### ISSUE TITLE
请问一下如何在中 Atmosphere 中配置代理服务器

### ISSUE THREAD

**Issue by hexgu** [huangqian8/SwitchScript#15]
我的网络是无法正常访问GitHub的，但是很多插件的更新和下载很大程度依赖GitHub

但是如果直接在“互联网”选项中配置代理服务器，会出现 DNS 由远端代理服务器进行解析，导致任天堂服务器屏蔽失败，然后我的 Atmosphere  就会 Error 2123-0011 (0x167b)

请问一下有什么好一点的解决方案吗

**Comment by huangqian8** [comment]
不建议直接在机器上使用代理，可以通过旁路由设置。
