### ISSUE TITLE
关于Lockpick_RCM和DBI

### ISSUE THREAD

**Issue by jackeyzzz12138** [huangqian8/SwitchScript#20]
1. [Lockpick_RCM](https://github.com/saneki/Lockpick_RCM) v1.9.3 已发布请作者更新plugins      

2. DBI由于7xx之后只支持俄语，为了使用上的方便，请问本仓库可否调换6xx最后一个版本，还是继续使用最新版？

**Comment by huangqian8** [comment]
等有空更新一下
