### ISSUE TITLE
小意见

### ISSUE THREAD

**Issue by Zhuwenxue2002** [huangqian8/SwitchScript#3]
非常感谢作者大大的整合,这个标明出处且都为原版特别特别好用,这里提一个小意见,就是推荐把switch-time插件整合到里面.因为默认是屏蔽掉任天堂端口的,所以就算联网也无法更新时间,导致时间是错误的.这款插件能联网更新时间,也可以手动调整系统时间,非常好用.
[github链接](https://github.com/3096/switch-time)
还有就是想问问作者,整合包中的大气层三件套在线升级工具,我打开之后直接就闪退崩溃了.所以想请教一下这个插件的使用方法,我去原版主页也是没看懂如何使用
再就是我认为那个重启和关闭系统的插件可以精简,因为特斯拉里包含此功能且非常好用

最后,我建议可以把hbmenu前端菜单也直接整合进整合包里面,这样的话就可以在整合之后即可正常使用awoo插件和checkpoint插件(虽然jskv更好用一些)

**Comment by huangqian8** [comment]
感谢建议！
switch-time和hbmenu已集成。
