### ISSUE TITLE
插件推荐

### ISSUE THREAD

**Issue by Zhuwenxue2002** [huangqian8/SwitchScript#6]
此插件应该可以完美替换掉大气层三件套升级插件，
https://github.com/HamletDuFromage/aio-switch-updater
其次，这个插件可以更多的应用于游戏的升级，金手指的在线下载
我使用大气层三件套升级插件相当难用

是否考虑继承wiliwili
https://github.com/xfangfang/wiliwili/releases
此插件可以在线观看b站视频

**Comment by Zhuwenxue2002** [comment]
还有此插件
https://github.com/PoloNX/SimpleModDownloader
可以实现在线下载一些游戏的mod
这三个插件都是有自带中文的

**Comment by huangqian8** [comment]
感谢推荐，已集成。

**Comment by Zhuwenxue2002** [comment]
大佬，我这边发现一个问题也挺想问问您的，有一些插件是需要挂代理才能使用。使用v2ray的方式链接http代理会不会让机器本身的dns屏蔽失效？

**Comment by Zhuwenxue2002** [comment]
是因为我用了咱们的整合包之后，挂代理联网后出现问题了 ，报错
![Uploading IMG_20240116_121901.jpg…]()

**Comment by Zhuwenxue2002** [comment]
有大佬分析，这是因为代理让dns屏蔽失效，检测到被隐藏序列号而出现的问题。像这种情况还可以挂代理使用么？ http到底会不会让dns代理失效呢

**Comment by huangqian8** [comment]
看不到错误提示？具体是哪个插件问题？

**Comment by Zhuwenxue2002** [comment]
大佬，我解决了问题，，并且证实了一个事情，就是挂代理会让本地的90dns的防ban失效，这会使被隐藏的序列号暴露在任天堂，然而17.0.0.1这个版本系统把空序列号作为严重的错误，才会报错。所以大气层最好是不使用代理。
而有些用户再没挂代理的情况下也出现了这个报错 ，我看有些教程是让把隐藏序列号功能取消就会恢复，然而这样在挂代理之后就一定会ban机

**Comment by Zhuwenxue2002** [comment]
https://www.bilibili.com/video/BV1i94y1K7Cy/?spm_id_from=333.1365.list.card_archive.click
我录制一个有关此问题的视频并且上传了b站
