### ISSUE TITLE
bash脚本可能需要代理的支持才能正常运行

### ISSUE THREAD

**Issue by shinobako** [huangqian8/SwitchScript#7]
由于众所周知的原因，在cn大内网环境下，对github.com的访问会出现不稳定的现象。
在本脚本的体现就是，在使用curl命令拉取api.github.com这个还能稳定访问的地址下的json时，能正常拉取，但用curl拉取github.com下的脚本压缩包就会出现超时。
推荐在说明文档中添加“需要魔法冲浪环境”的批注（也不用寻思直接在bash里实现了，毕竟都自己折腾整合包了，魔法冲浪还用人教？doge）

**Comment by huangqian8** [comment]
折腾大气层，会访问github的，默认都会科学上网的。
感谢建议，后续补充说明一下。
